import pygame

from rpg.geometry import Position

FRAMES_PER_SECOND: int = 60
WINDOW_WIDTH: int = 1920
WINDOW_HEIGHT: int = 1080
TIMELINE_WIDTH: int = WINDOW_WIDTH
TIMELINE_HEIGHT: int = 100
WORKSPACE_WIDTH: int = WINDOW_WIDTH / 2
WORKSPACE_HEIGHT: int = WINDOW_HEIGHT - TIMELINE_HEIGHT
MOVIE_WIDTH: int = WORKSPACE_WIDTH
MOVIE_HEIGHT: int = WORKSPACE_HEIGHT
MOVIE_FPS: int = 30
BACKGROUND_COLOR: pygame.Color = pygame.Color(0, 0, 0)
GROUP_PANEL_WIDTH: int = 250
GROUP_PANEL_HEIGHT: int = 600
GROUP_PANEL_POSITION: Position = Position(10, 10)
ACTION_PANEL_WIDTH: int = WINDOW_WIDTH/1.5
ACTION_PANEL_HEIGHT: int = 80
ACTION_PANEL_POSITION: Position = Position(WINDOW_WIDTH/6, WINDOW_HEIGHT-ACTION_PANEL_HEIGHT)
RETURN_SPEED = 2
FRIENDS_NAMES: list[str] = [
    "Victor TRUONG",
    "Rébecca MOLARET",
    "Lucie LAURENT",
    "Jimi TRUONG",
    "Anthony GIRARDO",
    "Nicolas PIAR",
    "C... M... 3e",
]
